on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          # github-app-id: ${{ secrets.APP_ID }}
          # github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          # github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
          author-email: scala-steward[bot]@users.noreply.github.com
          author-name: scala-steward[bot]
          github-token: ${{ secrets.WORKFLOW_PAT }}
          branches: develop
          # repos-file: 'repositories.md'
          github-repository: 'thanhz/test-repo-2'
