on:
  workflow_dispatch:

name: Test some script

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Print some things
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read repositories from file
        id: read-repos
        run: |
            while IFS= read -r line; do
            repo_name=$(echo "$line" | sed 's/^- //')
            echo "Line: $repo_name"
            done < repositories.md
        shell: bash
