on:
  workflow_dispatch:

name: Test some script

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Print some things
    steps:
      - uses: actions/checkout@v3
      - name: Read repository list
        run: |
          REPOS=$(cat repos.md)
      - name: Loop through repositories
        run: |
          for repo in $REPOS; do
            echo repo
          done

      - name: Read repositories from file
        id: read-repos
        run: |
            repos_content=""
            while IFS= read -r line; do
            repo_name=$(echo "$line" | sed -e 's/^- //' -e 's/:develop//')
            repos_content+="$repo_name "
            done < repos.md
            echo -e "::set-output name=repos::$repos_content"
        shell: bash

      - name: Print the previous output
        run: |
          for repo in ${{ steps.read-repos.outputs.repos }}; do
            echo "Repo: $repo"
          done
        shell: bash
