on:
  workflow_dispatch:

name: Test some script

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Print some things
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: thanhz/test-repo1
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Read repositories from file
        id: read-repos
        run: |
            repos_content=""
            while IFS= read -r line; do
            repo_name=$(echo "$line" | sed -e 's/^- //' -e 's/:develop//')
            repos_content+="$repo_name "
            done < repos.md
            echo -e "::set-output name=repos::$repos_content"
        shell: bash

      - name: Print the previous output
        run: |
          for repo in ${{ steps.read-repos.outputs.repos }}; do
            echo "Repo: $repo"
          done
        shell: bash
