on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Test some script

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Launch Scala Steward
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read repositories from file
        id: read-repos
        run: |
            while IFS= read -r line; do
            echo "Line: $line"
            done < "$file"
        shell: bash
