name: Upsert `develop` branch

on:
  workflow_dispatch:
jobs:
  upsert-develop-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Rebase `develop` branch to latest `origin/master`
    steps:
      - name: Checkout & Rebase `develop` branch to latest `origin/main`
        run: |
          default_branch=$(gh api /repos/$repo -q '.default_branch')
          git clone -b develop --single-branch --depth 1 https://github.com/thanhz/${{ repo }}.git
          git config user.email "9700622+thanhz@users.noreply.github.com"
          git fetch origin/$default_branch
          git rebase origin/$default_branch
          git push -f origin scala-steward-dependencies 
          
